### ISSUE TITLE
Factors in My.stepwise.coxph

### ISSUE THREAD

**Issue by annette987** [cran/My.stepwise#1]
Does My.stepwise.coxph handle factors (categorical variables)? Each time it encounters factor, e.g. 'race', I get the following error message:

` Error in eval(predvars, data, env) : object 'race2' not found`

Do I need to convert the factors to another form?
Thanks.

**Comment by Fu-Chang** [comment]
As the author of the "My.stepwise" package of R, I thank you for raising the question.  The direct answer to your question is "No!".  Could you please define dummy variables manually for your categorical variables on the variable list, and then re-run the stepwise variable selection procedure using the 'My.stepwise.coxph( )' function?  Specifically, define a dummy variable for each level of a categorical variable as a factor with more than two levels using the 'ifelse( )' function.  For example,

my.data$Petal.Length.se4.5 <- ifelse(my.data$Petal.Length <= 4.5, 1, 0)
my.data$Petal.Length.b4.5.se6 <- ifelse(my.data$Petal.Length > 4.5 & my.data$Petal.Length <= 6, 1, 0)
my.data$Petal.Length.b6 <- ifelse(my.data$Petal.Length > 6, 1, 0)

Then, put all these three dummy variables, 'Petal.Length.se4.5', 'Petal.Length.b4.5.se6', and 'Petal.Length.b6', on the variable list to be selected.  By doing so, the 'My.stepwise.coxph( )' function would help you identify the 'best' reference category for the categorical variable as a factor with more than two levels during the stepwise variable selection procedure.

**Comment by svd09** [comment]
Thanks very much for this comment and explanation. I did spend a long time trying to understand why I was getting an error. @Fu-Chang Thanks very much for creating the package.

**Comment by gaborcsardi** [comment]
This is a read only mirror of CRAN, please see  the package authors in the `DESCRIPTION` file. Thanks!
