### ISSUE TITLE
Variance Inflating Factor

### ISSUE THREAD

**Issue by annette987** [cran/My.stepwise#3]
I am confused about the about the ouput regarding the Variance Inflating factor. E.g. here is a line from the output of my model:

```
--------------- Variance Inflating Factor (VIF) ---------------
Multicollinearity Problem: Variance Inflating Factor (VIF) is bigger than 10 (Continuous Variable) or is bigger than 2.5 (Categorical Variable)
   RVLT7_raw   Animal_raw LM_delay_raw          Age        gpcog     timedsts 
    1.233100     1.113537     1.243972     1.101530     1.036259     1.119306 
# -------------------------------------------------------------------------------------------------- 
```

It says that the VIF is bigger than 10, but all the values shown are just over 1.0. How should these be interpreted? (These are all numeric variables).
Thanks.

**Comment by Fu-Chang** [comment]
As the author of the "My.stepwise" package of R, I thank you for raising the question.  The values of variance inflating factor (VIF) ≥ 10 in continuous covariates or VIF ≥ 2.5 in categorical covariates indicate the occurrence of the multicollinearity problem among some of the covariates in the fitted regression model.  In your case, it's fine.  That is, your regression model does not suffer the multicollinearity problem.
